### ISSUE TITLE
leetcode的username/password无法正确输入

### ISSUE THREAD

**Issue by fastzhong** [Peng-YM/LeetCode-Anki#1]
基本上用的都是最新的版本
MacOS: 10.15.7
Chrome: Version 86.0.4240.111 (Official Build) (x86_64)
Python: 3.8.5

username框出现：YOUR_USERNAME_HERE，随便敲1、2个字母，Chrome就自动关闭啦

**Comment by Peng-YM** [comment]
不好意思哦，昨天刚刚改了逻辑，现在麻烦重新Clone一下仓库。出于安全原因，现在用户名和密码不再保存`project.conf`了。
